<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.dell.delta_uat_automation.testcases.TC_1341378_LA_Review_Address_Dynamic_Dispatch_Postal_Code_blank_LA_UX" tests="1" time="572.902" ignored="0" failures="1" timestamp="07 Mar 2017 05:46:42 GMT" skipped="0" hostname="W10DMLDT12" errors="0">
  <testcase name="validate_TC_1341378_LA_Review_Address_Dynamic_Dispatch_Postal_Code_blank_LA_UX" time="572.902" classname="com.dell.delta_uat_automation.testcases.TC_1341378_LA_Review_Address_Dynamic_Dispatch_Postal_Code_blank_LA_UX">
    <failure type="java.lang.AssertionError" message="Caught/Error on clicking on Alert Dispatch :">
      <![CDATA[java.lang.AssertionError: Caught/Error on clicking on Alert Dispatch :
	at org.testng.Assert.fail(Assert.java:94)
	at com.dell.delta_uat_automation.workflows.NewDispatchWorkFlow.click_Dispatch_Alert(NewDispatchWorkFlow.java:546)
	at com.dell.delta_uat_automation.testcases.TC_1341378_LA_Review_Address_Dynamic_Dispatch_Postal_Code_blank_LA_UX.validate_TC_1341378_LA_Review_Address_Dynamic_Dispatch_Postal_Code_blank_LA_UX(TC_1341378_LA_Review_Address_Dynamic_Dispatch_Postal_Code_blank_LA_UX.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- validate_TC_1341378_LA_Review_Address_Dynamic_Dispatch_Postal_Code_blank_LA_UX -->
</testsuite> <!-- com.dell.delta_uat_automation.testcases.TC_1341378_LA_Review_Address_Dynamic_Dispatch_Postal_Code_blank_LA_UX -->
